services:
  - type: web
    name: cyberguard-cybersecurity-training
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py ensure_profiles && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz/
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "cyberguard-cybersecurity-training.onrender.com"
      - key: FRONTEND_URL
        value: "https://cyberguard-cybersecurity-training.vercel.app"
      - key: DATABASE_URL
        sync: false
